[book]
authors = ["Dave Henthorn"]
language = "en"
multilingual = false
src = "src"
title = "PracSec@RHIT"

[build]
build-dir = "docs"  
create-missing = false 

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "navy"
site-url = "/pracsec/"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.playground]
editable = false        
copyable = true  
